### ISSUE TITLE
Support other mods carpets

### ISSUE THREAD

**Issue by cech12** [EndlesNights/CarpetStairsMod#10]
Hey, I am the developer of the mod Extended Mushrooms. There I add carpets for every mushroom cap block. I like your mod and it would be nice if there is a possiblity to add these to a tag or something else to be supported in your mod. :)

**Comment by EndlesNights** [comment]
I don't have anything set up that just lets you tag blocks, but I might look into it for the future .
So that said I still really like your mod so I added support for it. I hope this helps more people discover it.

![2020-05-03_21 32 18](https://user-images.githubusercontent.com/58280840/80932537-e29bfc00-8d8d-11ea-9f8e-da53c2797cd8.png)

**Comment by cech12** [comment]
Thanks a lot for supporting my mod!! :D Maybe in the future I will add some more mushrooms. So it would be great, if the tag system will come some day. :D
