### ISSUE TITLE
Slight Render Issue

### ISSUE THREAD

**Issue by Ravin890** [EndlesNights/CarpetStairsMod#11]
If a carpet is on a lower slab it will not render the side of another carpet if its is half a slab higher.

![2020-05-06_20 20 27](https://user-images.githubusercontent.com/13302573/81241058-3c433700-8fd7-11ea-8fa0-317af92e5ed6.png)

*Side thing as well; since it looks like the carpet being 1 pixel too high would it be possible to lower it slightly to make it so you can place a block directly above it as opposed to having a 1 block gap (test by placing a carpet on a carpet slab or stair and test distances.

Additional Info:
Minecraft: 1.15.2
Forge: 3.1.11.77
Mod Version: 1.4.3
No other mods included in instance when test was done.

**Comment by EndlesNights** [comment]
Main issue has been fixed.

As for the second issue. No can do, so the way the mod works; the "carpets slab block" is not sharing the same space as the slab, but is taking up the spot of the block above it. The reason for the hitbox appearing to be one pixel too high is due to some wonkiness in MCs code where the game doesn't like to register hit boxes that are entirely outside of where the block is located. So it was done as a convenience so users could still click on said blocks. 
Now could I have made the mod so that the carpet and slabs are part of the same block and users could use the above space? Yes, but there are some other drawbacks with that approach, firstly I would have to override every slab in the game which is a lot of work, and then every new slab type would require a custom block state for every carpet type. Lastly and most major reason, if you were to ever remove the mod, every slab/stair with a carpet on it would be removed from your game, were as it is now you will only lose the carpets that cover the slabs/stairs.

Anyway thanks for the feed back, and sorry for any inconveniences.

**Comment by Ravin890** [comment]
no worries, I was curious about the 2nd thing honestly and was kinda wanting to pick your brain on that info XD the rendering thing was bothering me though.

**Comment by EndlesNights** [comment]
Oh it bothers me too, I'm just kinda surprised I've missed that case for so long. Well anyway hope you have a good day/night.

**Comment by Ravin890** [comment]
Was messing around with modpack I am throwing together and realized this mod could possibly help (it might be doing that overriding thing: https://www.curseforge.com/minecraft/mc-mods/snow-real-magic)
