### ISSUE TITLE
Carpet on stairs is difficult to break

### ISSUE THREAD

**Issue by WenXin20** [EndlesNights/CarpetStairsMod#3]
`Minecraft v1.14.4`
`Forge v28.2.0`
`Carpet Stairs v1.4`

- Wood floors and carpet that is placed on stairs can't be broken from the bottom step of the stairs, which makes it kinda difficult to break it.
- Also noticed that the selection box of the carpet intersects with the stairs on the bottom step instead of stopping on the edge.

**Comment by EndlesNights** [comment]
There doesn't appear to be anything I can easily do about the ability to properly targeting and breaking of carpets/wood Floor from the bottom step without rewriting how all staircase blocks work, or how hit detection works.

I can however fix the send issue of the bottom step being too large and clipping into the top step.

**Comment by WenXin20** [comment]
Alright, thanks. Is that the same way with Torch Slabs, for torches on the side of slabs at least?

**Comment by EndlesNights** [comment]
The issue seems more related to when the bounding box is outside of the designated 1㎥ area it starts to act a little wonky even if they're drawn them properly. So the wall slab Torches are mostly unaffected because they are essentially in the same position of a regular wall torch. This is why the carpet slab bounding box is so tall, because you can only actually select the top part of it that is within the actual area where the block is located. If it matched the blocks model you would be unable to select it.

**Comment by WenXin20** [comment]
That's too bad. Well, feel free to close if there's nothing else that can be done.
